
# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
  name: project-pool 

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '0a2f0091-7bc3-4277-be2b-7177e3ddac48'
  imageRepository: 'reactacr1'
  containerRegistry: 'reactacr1.azurecr.io'
  dockerfile: '$(Build.SourcesDirectory)/Dockerfile' 
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: Docker@2  # Using Docker@2 as it's generally more up-to-date
      displayName: Build an image
      inputs:
        command: build
        dockerfile: $(dockerfile) 
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push docker image to container registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection) 
        tags: |
          $(tag) 