
# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
  name: project-pool 

variables:
  # Container registry service connection established during pipeline creation
  containerregistrytype: 'Azure Container Registry'
  azureContainerRegistry: '{"loginServer":"registrytestt.azurecr.io", "id" : "/subscriptions/f9975a12-2adb-465a-a9c1-83e85eabbfc5/resourceGroups/React/providers/Microsoft.ContainerRegistry/registries/registrytestt"}'
  imageRepository: 'project1React'
  containerRegistry: 'reactacr1.azurecr.io'
  dockerfile: '$(Build.SourcesDirectory)/Dockerfile' 
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
  
  steps: 
  - task: Docker@1
    displayName: Building an Image
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      repository: $(imageRepository)
      displayName: Build
      tags: |
        $(tag)

  - task: DockerCompose@2
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'Free Trial(f9975a12-2adb-465a-a9c1-83e85eabbfc5)'
      azureContainerRegistry: '{"loginServer":"registrytestt.azurecr.io", "id" : "/subscriptions/f9975a12-2adb-465a-a9c1-83e85eabbfc5/resourceGroups/React/providers/Microsoft.ContainerRegistry/registries/registrytestt"}'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Run a Docker Compose command'
      dockerComposeCommand: 'docker stack deploy -c docker-compose.yml nginx-react'