
# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

pool:
  name: 'project-pool' # Adjust as needed for your Azure Pipelines agent

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '83e85eabbfc5'
  azureSubscription: 'project1React' # Subscription name in Azure
  azureContainerRegistry: '{"loginServer":"project1react.azurecr.io", "id" : "/subscriptions/f9975a12-2adb-465a-a9c1-83e85eabbfc5/resourceGroups/React/providers/Microsoft.ContainerRegistry/registries/project1React"}'
  imageRepository: 'reactacr1'
  containerRegistry: 'reactacr1.azurecr.io'
  dockerfile: '$(Build.SourcesDirectory)/Dockerfile' 
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build 
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: Docker@2  # Using Docker@2 as it's generally more up-to-date
      displayName: Build an image
      inputs:
        command: build
        dockerfile: $(dockerfile) 
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push docker image to container registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnection) 
        tags: |
          $(tag) 